

import { useEffect, useCallback, useRef } from 'react';
import { useUser } from '@clerk/nextjs';
import { useWebSocketStore, WSMessage } from '@/stores/websocket-store';

const WS_URL = process.env.NEXT_PUBLIC_WS_URL || 'wss://websocket.avai.life/ws';

export function useWebSocket() {
  const { user, isSignedIn } = useUser();
  const {
    isConnected,
    isConnecting,
    lastError,
    reconnectAttempts,
    connect,
    disconnect,
    sendMessage,
    subscribe,
  } = useWebSocketStore();
  
  const messageQueue = useRef<WSMessage[]>([]);
  
  // Generate persistent client ID using Clerk user ID when available
  const persistentClientId = useRef<string>('');
  
  // Initialize client ID using Clerk user data
  useEffect(() => {
    if (user?.id && !persistentClientId.current.includes(user.id)) {
      // Use Clerk user ID for authenticated users (persistent across sessions)
      persistentClientId.current = `avai_user_${user.id}`;
      console.log('🆔 Using Clerk user ID as client ID:', persistentClientId.current);
    } else if (!user && !persistentClientId.current) {
      // Generate anonymous ID for non-authenticated users (session-persistent)
      persistentClientId.current = `anon_${Math.random().toString(36).substr(2, 12)}`;
      console.log('🆔 Generated anonymous client ID:', persistentClientId.current);
    }
  }, [user]);

  // Static mode - no auto-connection
  useEffect(() => {
    console.log('🔌 WebSocket hook loaded (static mode - no auto-connection)');
    // No auto-connection in static mode
  }, []); // Runs once on mount

  // Only disconnect when user signs out
  useEffect(() => {
    if (!isSignedIn && isConnected) {
      disconnect();
    }

    // Cleanup on unmount
    return () => {
      if (!isSignedIn) {
        disconnect();
      }
    };
  }, [isSignedIn, isConnected, disconnect]);

  // Process queued messages when connected
  const processQueuedMessages = useCallback(() => {
    if (isConnected && messageQueue.current.length > 0) {
      const messages = [...messageQueue.current];
      messageQueue.current = [];
      
      messages.forEach(message => {
        sendMessage(message);
      });
    }
  }, [isConnected, sendMessage]);

  // Process queued messages when connected
  useEffect(() => {
    if (isConnected) {
      processQueuedMessages();
    }
  }, [isConnected, processQueuedMessages]);

  // Subscribe to messages with callback
  const subscribeToMessages = useCallback(
    (callback: (message: WSMessage) => void) => {
      return subscribe(callback);
    },
    [subscribe]
  );

  // Manual connect function
  const manualConnect = useCallback(() => {
    if (!isConnected && !isConnecting) {
      connect(WS_URL);
    }
  }, [isConnected, isConnecting, connect]);

  // Manual disconnect function
  const manualDisconnect = useCallback(() => {
    if (isConnected) {
      disconnect();
    }
  }, [isConnected, disconnect]);

  // Send analysis request with static response (bypassing WebSocket)
  const sendAnalysisRequest = useCallback(
    (prompt: string, sessionId?: number): boolean => {
      // For static mode, always return true immediately
      console.log('sendAnalysisRequest called with static mode - returning success immediately');
      console.log('Prompt:', prompt);
      console.log('Session ID:', sessionId);
      
      // The actual response will be generated by use-real-time-messages hook
      return true;
    },
    [user]
  );

  return {
    isConnected,
    isConnecting,
    lastError,
    reconnectAttempts,
    connect: manualConnect,
    disconnect: manualDisconnect,
    sendAnalysisRequest,
    subscribeToMessages,
  };
}