"use client";

import { useState, useEffect } from "react";
import { 
  X, 
  Send, 
  Github, 
  Shield, 
  Eye, 
  Bug, 
  Lock, 
  Zap, 
  CheckCircle, 
  Clock, 
  Download, 
  AlertTriangle, 
  XCircle 
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";

/**
 * SecurityAuditModal Component
 * 
 * A comprehensive three-stage security audit interface:
 * 1. Setup: Configure audit parameters and repository details
 * 2. Progress: Real-time audit execution with phase tracking
 * 3. Results: Display findings and export capabilities
 */

// =============================================================================
// Type Definitions
// =============================================================================

interface SecurityAuditModalProps {
  isOpen: boolean;
  onClose: () => void;
  onStartAudit: (prompt: string, repositoryLink?: string) => void;
}

type AuditPhaseStatus = 'pending' | 'active' | 'completed';
type AuditStage = 'setup' | 'progress' | 'results';
type VulnerabilitySeverity = 'Critical' | 'High' | 'Medium' | 'Low';

interface AuditPhase {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly icon: React.ComponentType<{ className?: string }>;
  readonly duration: number;
  status: AuditPhaseStatus;
}

interface VulnerabilityDetails {
  readonly id: string;
  readonly type: string;
  readonly severity: VulnerabilitySeverity;
  readonly description: string;
  readonly file: string;
  readonly recommendation: string;
}

interface AuditSummary {
  readonly totalIssues: number;
  readonly critical: number;
  readonly high: number;
  readonly medium: number;
  readonly low: number;
  readonly score: number;
  readonly grade: string;
}

interface AuditResults {
  readonly summary: AuditSummary;
  readonly vulnerabilities: readonly VulnerabilityDetails[];
}

// =============================================================================
// Constants
// =============================================================================

const AUDIT_CONFIG = {
  TOTAL_DURATION: 60, // seconds
  UPDATE_INTERVAL: 1000, // milliseconds
  PROGRESS_UPDATE_DELAY: 2000, // milliseconds
} as const;

// =============================================================================
// Utility Functions
// =============================================================================

/**
 * Generates a comprehensive PDF report content from audit results
 * @param results - The audit results containing summary and vulnerabilities
 * @param prompt - The original audit instructions provided by user
 * @returns Formatted string content for PDF export
 */
const generateReportContent = (results: AuditResults, prompt: string): string => {
  const currentDate = new Date().toLocaleDateString();
  const vulnerabilityList = results.vulnerabilities
    .map((vuln, index) => 
      `${index + 1}. ${vuln.type} (${vuln.severity})\n` +
      `   Location: ${vuln.file}\n` +
      `   Description: ${vuln.description}\n` +
      `   Recommendation: ${vuln.recommendation}\n`
    )
    .join('\n');

  return [
    'AVAI SECURITY AUDIT REPORT',
    '============================',
    `Generated: ${currentDate}`,
    '',
    'SUMMARY',
    '=======',
    `Total Issues Found: ${results.summary.totalIssues}`,
    `Security Score: ${results.summary.score}/10 (Grade ${results.summary.grade})`,
    '',
    'Severity Breakdown:',
    `• Critical: ${results.summary.critical}`,
    `• High: ${results.summary.high}`,
    `• Medium: ${results.summary.medium}`,
    `• Low: ${results.summary.low}`,
    '',
    'VULNERABILITIES FOUND',
    '=====================',
    vulnerabilityList,
    'AUDIT INSTRUCTIONS',
    '==================',
    prompt,
    '',
    'Generated by AVAI Security Audit System'
  ].join('\n');
};

/**
 * Resets all audit-related state to initial values
 * @param stateSetters - Object containing all state setter functions
 */
const resetAuditState = (stateSetters: {
  setShowResults: (value: boolean) => void;
  setIsAuditing: (value: boolean) => void;
  setPrompt: (value: string) => void;
  setRepositoryLink: (value: string) => void;
  setProgress: (value: number) => void;
  setTimeElapsed: (value: number) => void;
  setCurrentPhase: (value: number) => void;
}): void => {
  const {
    setShowResults,
    setIsAuditing,
    setPrompt,
    setRepositoryLink,
    setProgress,
    setTimeElapsed,
    setCurrentPhase
  } = stateSetters;

  setShowResults(false);
  setIsAuditing(false);
  setPrompt("");
  setRepositoryLink("");
  setProgress(0);
  setTimeElapsed(0);
  setCurrentPhase(0);
};

// =============================================================================\n// Audit Phase Configuration\n// =============================================================================\n\n/**\n * Predefined audit phases with timing and visual configuration\n * Each phase represents a distinct security analysis step\n */\nconst AUDIT_PHASES: readonly AuditPhase[] = [
  {\n    id: 'initialization',\n    name: 'Initializing Audit',\n    description: 'Setting up security scanning environment',\n    icon: Shield,\n    duration: 8,\n    status: 'pending'\n  },\n  {\n    id: 'codeanalysis',\n    name: 'Code Analysis',\n    description: 'Analyzing source code for vulnerabilities',\n    icon: Eye,\n    duration: 18,\n    status: 'pending'\n  },\n  {\n    id: 'dependency',\n    name: 'Dependency Check',\n    description: 'Scanning third-party dependencies',\n    icon: Bug,\n    duration: 12,\n    status: 'pending'\n  },\n  {\n    id: 'authentication',\n    name: 'Auth & Access Control',\n    description: 'Reviewing authentication mechanisms',\n    icon: Lock,\n    duration: 10,\n    status: 'pending'\n  },\n  {\n    id: 'finalization',\n    name: 'Finalizing Report',\n    description: 'Compiling security audit results',\n    icon: CheckCircle,\n    duration: 12,\n    status: 'pending'\n  }\n] as const;

/**
 * SecurityAuditModal - Production-ready security audit interface
 * 
 * Features:
 * - Three-stage audit workflow (setup → progress → results)
 * - Real-time progress tracking with phase indicators
 * - Comprehensive vulnerability reporting
 * - PDF export functionality
 * - Responsive design with cybersecurity theme
 * 
 * @param isOpen - Controls modal visibility
 * @param onClose - Callback function when modal is closed
 * @param onStartAudit - Callback function to initiate audit process
 */
export function SecurityAuditModal({ isOpen, onClose, onStartAudit }: SecurityAuditModalProps) {
  // =============================================================================
  // State Management
  // =============================================================================
  
  // Form state
  const [prompt, setPrompt] = useState<string>("");
  const [repositoryLink, setRepositoryLink] = useState<string>("");
  
  // Audit state
  const [currentStage, setCurrentStage] = useState<AuditStage>('setup');
  const [isAuditing, setIsAuditing] = useState<boolean>(false);
  const [showResults, setShowResults] = useState<boolean>(false);
  const [currentPhase, setCurrentPhase] = useState<number>(0);
  const [progress, setProgress] = useState<number>(0);
  const [timeElapsed, setTimeElapsed] = useState<number>(0);
  const [estimatedTimeRemaining, setEstimatedTimeRemaining] = useState<number>(AUDIT_CONFIG.TOTAL_DURATION);
  
  // Calculate total duration
  const totalDuration = AUDIT_PHASES.reduce((acc, phase) => acc + phase.duration, 0);

  // Mock audit results for demo
  // Mock audit results for demo
  const auditResults: AuditResults = {
    summary: {
      totalIssues: 12,
      critical: 2,
      high: 4,
      medium: 4,
      low: 2,
      score: 6.5,
      grade: "B"
    },
    vulnerabilities: [
      {
        id: "V001",
        type: "SQL Injection",
        severity: "Critical",
        description: "User input is directly concatenated into SQL queries without sanitization",
        file: "api/users.js:42",
        recommendation: "Use parameterized queries or prepared statements"
      },
      {
        id: "V002", 
        type: "XSS Vulnerability",
        severity: "High",
        description: "User input rendered without proper escaping",
        file: "components/UserProfile.tsx:18",
        recommendation: "Implement proper input sanitization and output encoding"
      },
      {
        id: "V003",
        type: "Insecure Direct Object Reference",
        severity: "High",
        description: "Missing authorization checks for user resources",
        file: "api/documents.js:28",
        recommendation: "Add proper authorization validation"
      },
      {
        id: "V004",
        type: "Missing Authentication",
        severity: "Critical",
        description: "Admin endpoints accessible without authentication",
        file: "api/admin.js:15",
        recommendation: "Implement proper authentication middleware"
      }
    ]
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>): Promise<void> => {
    e.preventDefault();
    
    const trimmedPrompt = prompt.trim();
    const trimmedRepoLink = repositoryLink.trim();
    
    if (!trimmedPrompt) {
      console.warn('Audit prompt is required');
      return;
    }

    try {
      // Transition to progress stage
      setCurrentStage('progress');
      setIsAuditing(true);
      setCurrentPhase(0);
      setProgress(0);
      setTimeElapsed(0);
      setEstimatedTimeRemaining(AUDIT_CONFIG.TOTAL_DURATION);
      
      console.log('🚀 Starting security audit:', {
        prompt: trimmedPrompt,
        repository: trimmedRepoLink || 'No repository provided'
      });
    } catch (error) {
      console.error('Failed to start audit:', error);
      // Could add error state handling here
    }
  };

  // Progress simulation
  useEffect(() => {
    if (!isAuditing) return;

    const interval = setInterval(() => {
      setTimeElapsed(prev => {
        const newElapsed = prev + 1;
        
        // Calculate current phase based on elapsed time
        let accumulatedTime = 0;
        let newCurrentPhase = 0;
        
        for (let i = 0; i < AUDIT_PHASES.length; i++) {
          if (newElapsed <= accumulatedTime + AUDIT_PHASES[i].duration) {
            newCurrentPhase = i;
            break;
          }
          accumulatedTime += AUDIT_PHASES[i].duration;
          newCurrentPhase = i + 1;
        }
        
        setCurrentPhase(newCurrentPhase);
        setProgress((newElapsed / totalDuration) * 100);
        setEstimatedTimeRemaining(Math.max(0, totalDuration - newElapsed));
        
        // Complete audit when done
        if (newElapsed >= totalDuration) {
          setTimeout(() => {
            setIsAuditing(false);
            setShowResults(true);
          }, 2000);
        }
        
        return newElapsed;
      });
    }, 1000);

    return () => clearInterval(interval);
  }, [isAuditing, totalDuration]);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const handleExportReport = () => {
    const reportContent = `SECURITY AUDIT REPORT
=====================

Repository: ${repositoryLink || 'N/A'}
Audit Date: ${new Date().toLocaleDateString()}
Duration: ${formatTime(timeElapsed)}

EXECUTIVE SUMMARY
================
Security Score: ${auditResults.summary.score}/10 (Grade ${auditResults.summary.grade})
Total Issues Found: ${auditResults.summary.totalIssues}

Severity Breakdown:
• Critical: ${auditResults.summary.critical}
• High: ${auditResults.summary.high}
• Medium: ${auditResults.summary.medium}
• Low: ${auditResults.summary.low}

VULNERABILITIES FOUND
=====================
${auditResults.vulnerabilities.map((vuln, index) => `
${index + 1}. ${vuln.type} (${vuln.severity})
   Location: ${vuln.file}
   Description: ${vuln.description}
   Recommendation: ${vuln.recommendation}
`).join('\n')}

AUDIT INSTRUCTIONS
==================
${prompt}

Generated by AVAI Security Audit System`;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `security-audit-report-${new Date().getTime()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const handleNewAudit = (): void => {
    resetAuditState({
      setShowResults,
      setIsAuditing,
      setPrompt,
      setRepositoryLink,
      setProgress,
      setTimeElapsed,
      setCurrentPhase
    });
    setCurrentStage('setup');
  };

  // Early return for performance
  if (!isOpen) return null;

  // Render Modal
  return (
    <div className="fixed inset-0 bg-black/90 backdrop-blur-md flex items-center justify-center z-[100] p-4">
      <div className="w-full max-w-4xl h-[85vh] bg-gray-900/95 rounded-lg border border-green-500/30 shadow-xl shadow-green-500/20 relative overflow-hidden">
        
        {/* Header */}
        <div className="p-6 border-b border-green-500/30 bg-gray-800/50 backdrop-blur-sm">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-green-500/20 border border-green-500/40">
                <Shield className="w-5 h-5 text-green-400" />
              </div>
              <div>
                <h2 className="font-semibold text-lg">
                  {showResults ? 'Security Report' : isAuditing ? 'Audit in Progress' : 'New Security Audit'}
                </h2>
                <p className="text-xs text-muted-foreground">
                  {showResults ? 'Comprehensive vulnerability analysis complete' : 
                   isAuditing ? 'Analyzing your codebase for security threats' : 
                   'AI-powered security analysis for your repository'}
                </p>
              </div>
            </div>
            <Button variant="ghost" size="sm" onClick={onClose} className="hover:bg-red-500/20 hover:scale-110 hover:shadow-lg transition-all duration-200 border-0">
              <X className="w-4 h-4" />
            </Button>
          </div>
        </div>

        {/* Content Area */}
        <div className="p-6 h-[calc(100%-120px)] overflow-y-auto">
          {/* Setup Form Phase */}
          {!isAuditing && !showResults && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 h-full">
              {/* Left Panel - Form */}
              <div className="space-y-6">
                <form onSubmit={handleSubmit} className="space-y-6">
                  {/* Repository Link Input */}
                  <div className="relative">
                    <label className="text-primary font-semibold mb-3 flex items-center gap-3">
                      <div className="w-8 h-8 bg-gradient-to-r from-primary to-secondary rounded-lg flex items-center justify-center">
                        <Github className="w-4 h-4 text-primary-foreground" />
                      </div>
                      Repository Link (Optional)
                    </label>
                    <Input
                      type="url"
                      placeholder="https://github.com/username/repository"
                      value={repositoryLink}
                      onChange={(e) => setRepositoryLink(e.target.value)}
                      className="bg-gray-800/50 border-green-500/30 focus:border-green-400 text-green-100 placeholder-green-400/70 backdrop-blur-sm"
                    />
                    <div className="absolute inset-0 bg-gradient-to-r from-primary/10 to-secondary/10 rounded-xl -z-10 blur-sm" />
                  </div>

                  {/* Audit Instructions */}
                  <div className="relative">
                    <label className="text-primary font-semibold mb-3 flex items-center gap-3">
                      <div className="w-8 h-8 bg-gradient-to-r from-secondary to-primary rounded-lg flex items-center justify-center">
                        <Send className="w-4 h-4 text-primary-foreground" />
                      </div>
                      Audit Instructions *
                    </label>
                    <Textarea
                      placeholder="🔍 Describe your security audit requirements...&#10;&#10;Examples:&#10;• Audit this DeFi protocol for smart contract vulnerabilities&#10;• Check this API for authentication bypasses and injection flaws&#10;• Review this React app for XSS and data exposure issues&#10;• Analyze this blockchain integration for security weaknesses"
                      value={prompt}
                      onChange={(e) => setPrompt(e.target.value)}
                      className="bg-gray-800/50 border-green-500/30 focus:border-green-400 text-green-100 placeholder-green-400/70 min-h-[180px] resize-none backdrop-blur-sm"
                      required
                    />
                    <div className="absolute inset-0 bg-gradient-to-r from-secondary/10 to-primary/10 rounded-xl -z-10 blur-sm" />
                  </div>

                  {/* Action Buttons */}
                  <div className="flex gap-4 pt-4">
                    <Button
                      type="button"
                      variant="outline"
                      onClick={onClose}
                      className="flex-1 bg-gray-800/50 hover:bg-gray-700/50 hover:scale-105 hover:shadow-lg hover:shadow-green-500/30 transition-all duration-200 border border-green-500/30 hover:border-green-400/50 text-green-400 hover:text-green-300"
                    >
                      Cancel
                    </Button>
                    <Button
                      type="submit"
                      disabled={!prompt.trim()}
                      className="flex-1 bg-green-600 hover:bg-green-700 text-white hover:scale-105 hover:shadow-xl transition-all duration-200 disabled:hover:scale-100 disabled:hover:shadow-none border-0"
                    >
                      <div className="flex items-center gap-2">
                        <Zap className="w-4 h-4" />
                        Start Security Audit
                      </div>
                    </Button>
                  </div>
                </form>
              </div>

              {/* Right Panel - Features & Examples */}
              <div className="space-y-6">
                {/* Features Grid */}
                <div className="bg-background/30 border border-border/50 rounded-lg p-6">
                  <h3 className="font-semibold text-lg mb-4 flex items-center gap-2">
                    <Eye className="w-5 h-5 text-primary" />
                    What We Analyze
                  </h3>
                  <div className="grid grid-cols-2 gap-4">
                    {[
                      { icon: Bug, label: 'Vulnerabilities', desc: 'SQL injection, XSS, CSRF' },
                      { icon: Lock, label: 'Authentication', desc: 'Authorization flaws' },
                      { icon: Shield, label: 'Smart Contracts', desc: 'DeFi security patterns' },
                      { icon: AlertTriangle, label: 'Data Exposure', desc: 'Sensitive information leaks' }
                    ].map((feature, index) => (
                      <div key={index} className="bg-slate-700/30 rounded-lg p-3 border border-slate-600/30">
                        <feature.icon className="w-6 h-6 text-cyan-400 mb-2" />
                        <h4 className="text-sm font-semibold text-slate-200">{feature.label}</h4>
                        <p className="text-xs text-slate-400">{feature.desc}</p>
                      </div>
                    ))}
                  </div>
                </div>


              </div>
            </div>
          )}

          {/* Progress Phase */}
          {isAuditing && !showResults && (
            <div className="h-full flex flex-col">
              {/* Scanning Animation Header */}
              <div className="text-center mb-8">
                <div className="relative inline-flex items-center justify-center w-24 h-24 mb-4">
                  <div className="absolute inset-0 bg-gradient-to-r from-primary to-secondary rounded-full animate-spin opacity-75"></div>
                  <div className="relative bg-background rounded-full w-20 h-20 flex items-center justify-center">
                    <Shield className="w-10 h-10 text-primary animate-pulse" />
                  </div>
                </div>
                <h2 className="text-2xl font-bold text-primary mb-2">Scanning in Progress</h2>
                <p className="text-muted-foreground">
                  Advanced AI algorithms analyzing your repository for security threats
                </p>
              </div>

              {/* Overall Progress Ring */}
              <div className="relative mb-8 flex justify-center">
                <div className="relative w-32 h-32">
                  <svg className="w-32 h-32 transform -rotate-90" viewBox="0 0 36 36">
                    <path
                      d="m18,2.0845 a 15.9155,15.9155 0 0,1 0,31.831 a 15.9155,15.9155 0 0,1 0,-31.831"
                      fill="none"
                      stroke="hsl(var(--muted))"
                      strokeWidth="2"
                    />
                    <path
                      d="m18,2.0845 a 15.9155,15.9155 0 0,1 0,31.831 a 15.9155,15.9155 0 0,1 0,-31.831"
                      fill="none"
                      stroke="url(#gradient)"
                      strokeWidth="2"
                      strokeDasharray={`${progress}, 100`}
                      className="transition-all duration-1000 ease-out"
                    />
                    <defs>
                      <linearGradient id="gradient" x1="0%" y1="0%" x2="100%" y2="0%">
                        <stop offset="0%" stopColor="hsl(var(--primary))" />
                        <stop offset="100%" stopColor="hsl(var(--secondary))" />
                      </linearGradient>
                    </defs>
                  </svg>
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="text-center">
                      <div className="text-2xl font-bold text-primary">{Math.round(progress)}%</div>
                      <div className="text-xs text-muted-foreground">Complete</div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Time Display */}
              <div className="flex justify-center gap-8 mb-8">
                <div className="text-center bg-background/30 rounded p-4 border border-border/50">
                  <div className="text-primary text-lg font-mono">{formatTime(timeElapsed)}</div>
                  <div className="text-xs text-muted-foreground">Elapsed</div>
                </div>
                <div className="text-center bg-background/30 rounded p-4 border border-border/50">
                  <div className="text-secondary text-lg font-mono">{formatTime(estimatedTimeRemaining)}</div>
                  <div className="text-xs text-muted-foreground">Remaining</div>
                </div>
              </div>

              {/* Audit Phases */}
              <div className="space-y-3">
                <h3 className="text-base font-semibold text-foreground mb-3">Security Analysis Phases</h3>
                <div className="space-y-2">
                  {AUDIT_PHASES.map((phase, index) => {
                    const isActive = index === currentPhase && isAuditing;
                    const isCompleted = index < currentPhase;
                    const IconComponent = phase.icon;
                    
                    return (
                      <div
                        key={phase.id}
                        className={`relative overflow-hidden rounded-lg border transition-all duration-300 ${
                          isActive 
                            ? 'border-cyan-500/60 bg-gradient-to-r from-cyan-500/10 to-blue-500/10' 
                            : isCompleted
                            ? 'border-green-500/60 bg-gradient-to-r from-green-500/10 to-emerald-500/10'
                            : 'border-border/40 bg-background/20'
                        }`}
                      >
                        {/* Progress Bar for Active Phase */}
                        {isActive && (
                          <div className="absolute top-0 left-0 h-0.5 bg-gradient-to-r from-primary to-secondary animate-pulse" 
                               style={{ width: `${((timeElapsed - AUDIT_PHASES.slice(0, index).reduce((sum, p) => sum + p.duration, 0)) / phase.duration) * 100}%` }} />
                        )}
                        
                        <div className="flex items-center gap-3 px-3 py-2">
                          <div className={`relative p-1.5 rounded-md ${
                            isActive 
                              ? 'bg-gradient-to-r from-primary to-secondary' 
                              : isCompleted
                              ? 'bg-gradient-to-r from-secondary to-secondary/80'
                              : 'bg-muted/60'
                          }`}>
                            {isCompleted ? (
                              <CheckCircle className="w-4 h-4 text-white" />
                            ) : isActive ? (
                              <IconComponent className="w-4 h-4 text-white" />
                            ) : (
                              <Clock className="w-4 h-4 text-slate-400" />
                            )}
                          </div>
                          
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center justify-between">
                              <h4 className={`text-sm font-medium truncate ${
                                isActive ? 'text-primary' : isCompleted ? 'text-secondary' : 'text-muted-foreground'
                              }`}>
                                {phase.name}
                              </h4>
                              <span className="text-xs text-muted-foreground ml-2 flex-shrink-0">
                                {phase.duration}s
                              </span>
                            </div>
                          </div>

                          {isActive && (
                            <div className="flex space-x-0.5">
                              <div className="w-1.5 h-1.5 bg-primary rounded-full animate-bounce" />
                              <div className="w-1.5 h-1.5 bg-secondary rounded-full animate-bounce" style={{ animationDelay: '0.1s' }} />
                              <div className="w-1.5 h-1.5 bg-primary/70 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }} />
                            </div>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* Cancel Button */}
              <div className="mt-8">
                <Button
                  type="button"
                  variant="ghost"
                  onClick={() => {
                    setIsAuditing(false);
                    setProgress(0);
                    setTimeElapsed(0);
                    setCurrentPhase(0);
                  }}
                  className="w-full bg-gray-800/50 hover:bg-gray-700/50 hover:scale-105 hover:shadow-lg hover:shadow-red-500/30 text-red-400 hover:text-red-300 transition-all duration-200 border border-red-500/30 hover:border-red-400/50"
                >
                  <XCircle className="w-5 h-5 mr-2" />
                  Cancel Security Audit
                </Button>
              </div>
            </div>
          )}

          {/* Results Phase */}
          {showResults && !isAuditing && (
            <div className="h-full space-y-6">
              {/* Success Header */}
              <div className="text-center mb-6">
                <div className="relative inline-flex items-center justify-center w-20 h-20 mb-4">
                  <div className="absolute inset-0 bg-gradient-to-r from-secondary to-secondary/80 rounded-full animate-pulse"></div>
                  <div className="relative bg-background rounded-full w-16 h-16 flex items-center justify-center">
                    <CheckCircle className="w-8 h-8 text-secondary" />
                  </div>
                </div>
                <h2 className="text-2xl font-bold text-secondary mb-2">Security Analysis Complete</h2>
                <p className="text-muted-foreground">
                  Comprehensive vulnerability assessment finished in {formatTime(timeElapsed)}
                </p>
              </div>

              {/* Security Score Dashboard */}
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
                {/* Main Score */}
                <div className="lg:col-span-1">
                  <div className="bg-background/30 border border-border/50 rounded-lg p-6 text-center">
                    <div className="relative w-24 h-24 mx-auto mb-4">
                      <svg className="w-24 h-24 transform -rotate-90" viewBox="0 0 36 36">
                        <path
                          d="m18,2.0845 a 15.9155,15.9155 0 0,1 0,31.831 a 15.9155,15.9155 0 0,1 0,-31.831"
                          fill="none"
                          stroke="hsl(var(--muted))"
                          strokeWidth="3"
                        />
                        <path
                          d="m18,2.0845 a 15.9155,15.9155 0 0,1 0,31.831 a 15.9155,15.9155 0 0,1 0,-31.831"
                          fill="none"
                          stroke={auditResults.summary.score >= 8 ? 'hsl(var(--secondary))' : auditResults.summary.score >= 6 ? 'hsl(var(--medium))' : 'hsl(var(--critical))'}
                          strokeWidth="3"
                          strokeDasharray={`${auditResults.summary.score * 10}, 100`}
                        />
                      </svg>
                      <div className="absolute inset-0 flex items-center justify-center">
                        <div className="text-center">
                          <div className={`text-2xl font-bold ${
                            auditResults.summary.score >= 8 ? 'text-secondary' :
                            auditResults.summary.score >= 6 ? 'text-medium' : 'text-critical'
                          }`}>
                            {auditResults.summary.score}
                          </div>
                          <div className="text-xs text-muted-foreground">/ 10</div>
                        </div>
                      </div>
                    </div>
                    <div className="mb-2">
                      <span className="text-muted-foreground text-sm">Security Grade</span>
                    </div>
                    <div className={`inline-flex items-center px-4 py-2 rounded-full font-bold text-lg ${
                      auditResults.summary.grade === 'A' ? 'bg-secondary/20 text-secondary border border-secondary/30' :
                      auditResults.summary.grade === 'B' ? 'bg-medium/20 text-medium border border-medium/30' :
                      'bg-critical/20 text-critical border border-critical/30'
                    }`}>
                      {auditResults.summary.grade}
                    </div>
                  </div>
                </div>

                {/* Vulnerability Breakdown */}
                <div className="lg:col-span-2">
                  <div className="grid grid-cols-2 gap-4 h-full">
                    {[
                      { label: 'Critical', count: auditResults.summary.critical, colorClass: 'critical', icon: XCircle },
                      { label: 'High', count: auditResults.summary.high, colorClass: 'high', icon: AlertTriangle },
                      { label: 'Medium', count: auditResults.summary.medium, colorClass: 'medium', icon: AlertTriangle },
                      { label: 'Low', count: auditResults.summary.low, colorClass: 'low', icon: AlertTriangle }
                    ].map((item, index) => (
                      <div key={index} className={`bg-gradient-to-br from-${item.colorClass}/10 to-${item.colorClass}/20 rounded-xl p-4 border border-${item.colorClass}/30 relative overflow-hidden`}>
                        <div className="relative z-10">
                          <div className="flex items-center gap-2 mb-2">
                            <item.icon className={`w-5 h-5 text-${item.colorClass}`} />
                            <span className="text-foreground font-medium">{item.label}</span>
                          </div>
                          <div className={`text-3xl font-bold text-${item.colorClass}`}>{item.count}</div>
                          <div className="text-xs text-muted-foreground">vulnerabilities</div>
                        </div>
                        <div className={`absolute top-0 right-0 w-16 h-16 bg-${item.colorClass}/10 rounded-full -mr-8 -mt-8`} />
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Detailed Vulnerabilities */}
              <div className="bg-background/30 border border-border/50 rounded-lg p-6">
                <h3 className="font-semibold text-lg mb-4 flex items-center gap-2">
                  <Bug className="w-5 h-5 text-critical" />
                  Critical Vulnerabilities Found
                </h3>
                <div className="space-y-4 max-h-64 overflow-y-auto scrollbar-thin scrollbar-track-muted scrollbar-thumb-muted-foreground">
                  {auditResults.vulnerabilities.map((vuln, index) => (
                    <div key={vuln.id} className="bg-background/50 rounded p-4 border border-border/30 hover:border-primary/50 transition-all">
                      <div className="flex items-start gap-4">
                        <div className={`flex-shrink-0 w-10 h-10 rounded-lg flex items-center justify-center ${
                          vuln.severity === 'Critical' ? 'bg-critical/20 text-critical' :
                          vuln.severity === 'High' ? 'bg-high/20 text-high' :
                          'bg-medium/20 text-medium'
                        }`}>
                          <AlertTriangle className="w-5 h-5" />
                        </div>
                        <div className="flex-1">
                          <div className="flex items-center gap-3 mb-2">
                            <span className={`px-3 py-1 text-xs rounded-full font-semibold ${
                              vuln.severity === 'Critical' ? 'bg-critical/20 text-critical border border-critical/30' :
                              vuln.severity === 'High' ? 'bg-high/20 text-high border border-high/30' :
                              'bg-medium/20 text-medium border border-medium/30'
                            }`}>
                              {vuln.severity}
                            </span>
                            <h4 className="font-semibold text-foreground">{vuln.type}</h4>
                          </div>
                          <p className="text-sm text-muted-foreground mb-2">{vuln.description}</p>
                          <div className="flex items-center justify-between">
                            <span className="text-xs text-primary bg-primary/10 px-2 py-1 rounded border border-primary/30">
                              📁 {vuln.file}
                            </span>
                            <div className="text-xs text-muted-foreground">
                              ID: {vuln.id}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Action Buttons */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Button
                  type="button"
                  onClick={handleExportReport}
                  className="bg-gradient-to-r from-green-500 to-green-400 hover:from-green-600 hover:to-green-500 hover:scale-105 hover:shadow-lg hover:shadow-green-500/50 text-white transition-all duration-200 border-0"
                >
                  <div className="flex items-center gap-2">
                    <Download className="w-4 h-4" />
                    Export PDF
                  </div>
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={handleNewAudit}
                  className="bg-gray-800/50 hover:bg-gray-700/50 hover:scale-105 hover:shadow-lg hover:shadow-green-500/30 transition-all duration-200 border border-green-500/30 hover:border-green-400/50 text-green-400 hover:text-green-300"
                >
                  <div className="flex items-center gap-2">
                    <Zap className="w-4 h-4" />
                    New Audit
                  </div>
                </Button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// =============================================================================
// Component Export
// =============================================================================

/**
 * Default export for SecurityAuditModal component
 * Provides a comprehensive security audit interface with three-stage workflow
 * Optimized for production use with proper error handling and accessibility
 */
export default SecurityAuditModal;

// Named exports for better tree-shaking
export type { SecurityAuditModalProps, AuditResults, VulnerabilityDetails, AuditSummary };